// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXl94sb8Q5JF1AtgnSAEocZ8-dzmHix3A',
    appId: '1:222024203248:web:25ef06700243d1f76dfb35',
    messagingSenderId: '222024203248',
    projectId: 'domra-7b540',
    authDomain: 'domra-7b540.firebaseapp.com',
    storageBucket: 'domra-7b540.firebasestorage.app',
    measurementId: 'G-YY3916XF2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkDXiR1CZE7ylRBEGImZb7g3OK9e1Otuc',
    appId: '1:222024203248:android:92e92e21b26777786dfb35',
    messagingSenderId: '222024203248',
    projectId: 'domra-7b540',
    storageBucket: 'domra-7b540.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0B_tTxCVeBjmBPkt6QW55OHJXqaRJJSg',
    appId: '1:222024203248:ios:0bbd8628f18faa256dfb35',
    messagingSenderId: '222024203248',
    projectId: 'domra-7b540',
    storageBucket: 'domra-7b540.firebasestorage.app',
    iosClientId: '222024203248-v546o33h5clsoensc5p9o8370rp4rq11.apps.googleusercontent.com',
    iosBundleId: 'com.example.domraTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0B_tTxCVeBjmBPkt6QW55OHJXqaRJJSg',
    appId: '1:222024203248:ios:0bbd8628f18faa256dfb35',
    messagingSenderId: '222024203248',
    projectId: 'domra-7b540',
    storageBucket: 'domra-7b540.firebasestorage.app',
    iosClientId: '222024203248-v546o33h5clsoensc5p9o8370rp4rq11.apps.googleusercontent.com',
    iosBundleId: 'com.example.domraTech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXl94sb8Q5JF1AtgnSAEocZ8-dzmHix3A',
    appId: '1:222024203248:web:0408199b17a20d736dfb35',
    messagingSenderId: '222024203248',
    projectId: 'domra-7b540',
    authDomain: 'domra-7b540.firebaseapp.com',
    storageBucket: 'domra-7b540.firebasestorage.app',
    measurementId: 'G-JZNRGWKL5N',
  );
}
